ALTER TABLE metrics.etl_metadata
    ADD COLUMN IF NOT EXISTS app_id VARCHAR(225) NULL,
    ADD COLUMN IF NOT EXISTS build_id VARCHAR(225) NULL,
    ADD COLUMN IF NOT EXISTS instance_id VARCHAR(225) NULL,
    ADD COLUMN IF NOT EXISTS test_session_id VARCHAR(225) NULL,
    ADD COLUMN IF NOT EXISTS test_definition_id VARCHAR(225) NULL,
    ADD COLUMN IF NOT EXISTS test_launch_id VARCHAR(225) NULL;

