/**
 * Copyright 2020 - 2022 EPAM Systems
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.epam.drill.admin.writer.rawdata.entity
import kotlinx.serialization.Serializable

@Serializable
data class CoveragePayload(
    val instanceId: String,
    val coverage: Array<SingleClassCoveragePayload>,
) {
    // autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as CoveragePayload

        if (instanceId != other.instanceId) return false
        if (!coverage.contentEquals(other.coverage)) return false

        return true
    }
    // autogenerated
    override fun hashCode(): Int {
        var result = instanceId.hashCode()
        result = 31 * result + coverage.contentHashCode()
        return result
    }
}

@Serializable
data class SingleClassCoveragePayload(
    val classname: String,
    val testId: String,
    val probes: Array<Boolean>
) {
    // autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as SingleClassCoveragePayload

        if (classname != other.classname) return false
        if (testId != other.testId) return false
        if (!probes.contentEquals(other.probes)) return false

        return true
    }

    // autogenerated
    override fun hashCode(): Int {
        var result = classname.hashCode()
        result = 31 * result + testId.hashCode()
        result = 31 * result + probes.contentHashCode()
        return result
    }
}

data class Coverage(
    val instanceId: String,
    val classname: String,
    val testId: String,
    val probes: Array<Boolean>
) {
    // autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Coverage

        if (instanceId != other.instanceId) return false
        if (classname != other.classname) return false
        if (testId != other.testId) return false
        if (!probes.contentEquals(other.probes)) return false

        return true
    }

    // autogenerated
    override fun hashCode(): Int {
        var result = instanceId.hashCode()
        result = 31 * result + classname.hashCode()
        result = 31 * result + testId.hashCode()
        result = 31 * result + probes.contentHashCode()
        return result
    }
}