name: Check
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release/*'
      - 'merge/*'
      - 'adoption/*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'
  pull_request:
    branches:
      - 'main'
      - 'release/*'
      - 'feature/*'
      - 'merge/*'
      - 'adoption/*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  check:
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, preset: linuxX64}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set gradlew executable permission
        run: chmod +x gradlew
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.config.preset }}
          path: ${{ github.workspace }}/*/build/reports/*
