name: Check admin
on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
#      - name: Gradle Cache
#        id: cache-gradle
#        uses: actions/cache@v1
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#      - name: Gradle Build Cache
#        id: cache-build
#        uses: actions/cache@v1
#        with:
#          path: ./build-cache
#          key: ${{ runner.os }}-build-${{ hashFiles('**/*.gradle.kts') }}
#          restore-keys: |
#            ${{ runner.os }}-build-
      - name: Check
        run: |
          gradle -si check
