name: Check admin
on:
  pull_request:
    branches:
      - 'develop'
      - 'release/*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  check:
    if: false
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: echo '${{ toJSON(github.event.commits[0]) }}'
#      - uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: -s check
