name: Check
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release/*'
      - 'adoption/*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'
  pull_request:
    branches:
      - 'main'
      - 'release/*'
      - 'adoption/*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  check:
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, preset: linuxX64}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8.0
          distribution: zulu
      - uses: gradle/wrapper-validation-action@v1
      - if: matrix.config.preset == 'linuxX64'
        run: chmod +x ${{ github.workspace }}/gradlew
      - if: matrix.config.preset == 'linuxX64'
        run: chmod +x ${{ github.workspace }}/setup-shared-libs.sh
      - if: matrix.config.preset == 'linuxX64'
        run: sudo apt-get install -y libtinfo5
      - if: matrix.config.preset == 'linuxX64'
        run: ${{ github.workspace }}/setup-shared-libs.sh
      - if: matrix.config.preset == 'mingwX64'
        run: ${{ github.workspace }}/setup-shared-libs.bat
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check
      - if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ matrix.config.preset }}
          path: ${{ github.workspace }}/*/build/reports/*
