name: Build & publish drill artifacts
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Maven repo and Docker registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s test
      - name: Publish test report to artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: '~/**/test-results/**/*.xml'
      - name: Publish to Maven Repo
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish to DockerHub
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s jib
        env:
          GRADLE_OPTS: >
            -Djib.to.image=drill4j/admin
            -Djib.to.auth.username=${{ secrets.DRILL_USERNAME }}
            -Djib.to.auth.password=${{ secrets.DRILL_PASSWORD }}
      - name: Publish to GitHub Container registry
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s jib
        env:
          GRADLE_OPTS: >
            -Djib.to.image=ghcr.io/drill4j/admin
            -Djib.to.auth.username=${{ secrets.GH_PACKAGE_USERNAME }}
            -Djib.to.auth.password=${{ secrets.GH_PACKAGE_TOKEN }}
