name: Build & publish drill artifacts
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Maven repo and Docker registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s test
      - name: Publish to GitHub Container Registry
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s jib
        env:
          GRADLE_OPTS: >
            -Djib.to.auth.username=${{ secrets.GH_PACKAGE_USERNAME }}
            -Djib.to.auth.password=${{ secrets.GH_PACKAGE_TOKEN }}
