name: Tag develop
on:
  push:
    branches:
      - develop

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Next Prerelease SemVer
        id: next_semver
        uses: Drill4J/semver-tag-action@v0.1.0
        with:
          type: prerelease
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.githubUserPassword }}
          tag: v${{ steps.next_semver.outputs.tag }}
