name: Tag develop
on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - run: git fetch
      - name: Next Prerelease SemVer
        id: next_semver
        uses: Drill4J/semver-tag-action@v0.1.0
        with:
          type: prerelease
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}
          tag: ${{ steps.next_semver.outputs.tag }}
